---
layout: post
title: "Factory Design Pattern Case Study"
comments: true
---
<h3 class="post-title entry-title">I had a job to check our project code quality. And have to report it back to my team leader for any obstacle that i found in the project. I found a lot of leaks and i think would be good to be discussed on the blog. Not to mock the author, but to learn and improve ourselves together. <br /> <br /> Like this code, this is the part that i found in our code.</h3>
<p>&nbsp;</p>
<p><strong><span style="color: #0000ff;">public ContactInfoBean(final Reseller resellerInfo) {</span></strong><br /><br /><strong><span style="color: #0000ff;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; switch(resellerInfo.getType()) {</span></strong><br /><br /><strong><span style="color: #0000ff;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; case PROGRAM_CONTACT:</span></strong><br /><strong><span style="color: #0000ff;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; readExecutiveInfo(resellerInfo);</span></strong><br /><strong><span style="color: #0000ff;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; break;</span></strong><br /><strong><span style="color: #0000ff;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; case FILE_CONTACT:</span></strong><br /><strong><span style="color: #0000ff;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp; &nbsp; readOperationalInfo(resellerInfo);</span></strong><br /><strong><span style="color: #0000ff;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; break;</span></strong><br /><strong><span style="color: #0000ff;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; default:</span></strong><br /><br /><strong><span style="color: #0000ff;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; break;</span></strong><br /><br /><strong><span style="color: #0000ff;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; }</span></strong><br /><br /><strong><span style="color: #0000ff;">&nbsp;&nbsp; }</span></strong><br /><br /></p>
<p>The code works fine, and do its job pretty well. But some problem will appear by using this code-style. This class will grow tailing the biz changes, as usual, the bigger one class, the &ldquo;merrier&rdquo; to maintain it is. And most likely this class, will be having more than one purpose, can be called low-cohesion. <br /> <br /> <strong>Better OOP Approach</strong> <br /> <br /> Well the better approach for the case above would be using the Factory Design Pattern. We can let the factory of READER to generate every single instance according to their type. It would be easier to grow the instance type, since we just need to create a new class and do a little modification in the Factory class. The caller class, wont grow and will stand still at its current shape.</p>
<p><strong><span style="color: #0000ff;">public interface InfoReader {</span></strong><br /><br /><strong><span style="color: #0000ff;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; public void readInfo();</span></strong><br /><br /><strong><span style="color: #0000ff;">}</span></strong></p>
<p><br /><strong><span style="color: #0000ff;">public class ExecutiveReader implements <span style="color: #ff0000;">InfoReader</span> {</span></strong><br /><br /><strong><span style="color: #0000ff;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; public void <span style="color: #ff0000;">readInfo</span>() {</span></strong><br /><strong><span style="color: #0000ff;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; // override</span></strong><br /><strong><span style="color: #0000ff;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; }</span></strong><br /><br /><strong><span style="color: #0000ff;">}</span></strong></p>
<p>&nbsp;</p>
<p><br /><strong><span style="color: #0000ff;">public class OperationalReader implements <span style="color: #ff0000;">InfoReader</span> {</span></strong><br /><br /><strong><span style="color: #0000ff;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; public void <span style="color: #ff0000;">readInfo</span>() {</span></strong><br /><strong><span style="color: #0000ff;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; // override</span></strong><br /><strong><span style="color: #0000ff;">&nbsp; &nbsp; &nbsp; &nbsp; }</span></strong><br /><br /><strong><span style="color: #0000ff;">}</span></strong><br /><br /></p>
<p>And The Factory</p>
<p><strong><span style="color: #0000ff;">public class InfoReaderFactory {</span></strong><br /><br /><strong><span style="color: #0000ff;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; private static final int PROGRAM_CONTACT = 1;</span></strong><br /><br /><strong><span style="color: #0000ff;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; private static final int FILE_CONTACT = 2;</span></strong><br /><br /><strong><span style="color: #0000ff;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; public static InfoReader getInstance(Reseller resellerInfo) {</span></strong><br /><br /><strong><span style="color: #0000ff;">&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; InfoReader instance = null;</span></strong><br /><br /><strong><span style="color: #0000ff;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; switch (resellerInfo.getType()) {</span></strong><br /><br /><strong><span style="color: #0000ff;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; case PROGRAM_CONTACT:</span></strong><br /><br /><strong><span style="color: #0000ff;">&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp; instance = new ExecutiveReader();</span></strong><br /><br /><strong><span style="color: #0000ff;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; break;</span></strong><br /><br /><strong><span style="color: #0000ff;">&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp; case FILE_CONTACT:</span></strong><br /><br /><strong><span style="color: #0000ff;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; instance = new OperationalReader();</span></strong><br /><br /><strong><span style="color: #0000ff;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; break;</span></strong><br /><br /><strong><span style="color: #0000ff;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; default:</span></strong><br /><br /><strong><span style="color: #0000ff;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; throw new IllegalArgumentException('Unknown Reseller');</span></strong><br /><br /><strong><span style="color: #0000ff;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; }</span></strong><br /><br /><strong><span style="color: #0000ff;">&nbsp;&nbsp;&nbsp;&nbsp; return instance;</span></strong><br /><br /><strong><span style="color: #0000ff;">&nbsp;&nbsp; }</span></strong><br /><br /><strong><span style="color: #0000ff;">}</span></strong><br /><br /></p>
<p>And now The Caller</p>
<p><strong><span style="color: #0000ff;">InfoReader reader = InfoReaderFactory.getInstance(resellerInfo);</span></strong><br /><br /><strong><span style="color: #0000ff;">reader.readInfo();</span></strong><br /><br /></p>
<p><br /> <strong>The Benefits</strong> <br /> <br /> With the Factory Design Pattern to handle this case, we can achieve some benefits,</p>
<ul>
<li>Specifying a class for one task, means, easier to maintain since one class is for one purpose only (modularity/High Cohesion). i.e: Operational Reader is only to read data for Operational only, no other purpose. Just in case, one day in the future we need another Reader (say: NonOperationalReader). We just need create a new Class that extends (or implements) the InfoReader class and then we can override our own readInfo() function. This Caller class will have no impact. We just need to do some modification in the Factory code.</li>
</ul>
<p><br style="color: #0000ff;" /><strong><span style="color: #000080;">public class InfoReaderFactory {</span></strong><br /><strong><span style="color: #000080;">&nbsp;&nbsp;&nbsp; private static final int PROGRAM_CONTACT = 1;</span></strong><br /><strong><span style="color: #000080;">&nbsp;&nbsp;&nbsp; private static final int FILE_CONTACT = 2;</span></strong><br /><strong><span style="color: #000080;">&nbsp;&nbsp;&nbsp; private static final int NEW_READER = 3;</span></strong><br /><br /><strong><span style="color: #000080;">&nbsp;&nbsp;&nbsp; public static InfoReader getInstance(ResellerInfo resellerInfo) {</span></strong><br /><strong><span style="color: #000080;">&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp; InfoReader instance = null;</span></strong><br /><strong><span style="color: #000080;">&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp; switch (resellerInfo.getType()) {</span></strong><br /><strong><span style="color: #000080;">&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp; &nbsp; case PROGRAM_CONTACT:</span></strong><br /><strong><span style="color: #000080;">&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp; &nbsp; instance = new ExecutiveReader();</span></strong><br /><strong><span style="color: #000080;">&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp; &nbsp; break;</span></strong><br /><strong><span style="color: #000080;">&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp; &nbsp; case FILE_CONTACT:</span></strong><br /><strong><span style="color: #000080;">&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp; &nbsp; instance = new OperationalReader();</span></strong><br /><strong><span style="color: #000080;">&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp; &nbsp; break;</span></strong><br /><strong><span style="color: #000080;">&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp; &nbsp; case NEW_READER:</span></strong><br /><strong><span style="color: #000080;">&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp; &nbsp; instance = new NonOperationalReader();</span></strong><br /><strong><span style="color: #000080;">&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp; &nbsp; break;</span></strong><br /><strong><span style="color: #000080;">&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp; &nbsp; default:</span></strong><br /><strong><span style="color: #000080;">&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp; &nbsp; throw new IllegalArgumentException('Unknown Reseller');</span></strong><br /><strong><span style="color: #000080;">&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp; }</span></strong><br /><strong><span style="color: #000080;">&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp; return instance;</span></strong><br /><strong><span style="color: #000080;">&nbsp;&nbsp;&nbsp; }</span></strong><br /><strong><span style="color: #000080;">}</span></strong><br /><br /></p>
<p>Higher Reusability of Parent&rsquo;s Component (Inheritance): Since we have parent class (InfoReader), we can put common functions and thingies inside this InfoReader class, and later all of the derivative classes (ExecutiveReader and OperationalReader) can reuse the common components from InfoReader . Avoid code redundancy and can minimize coding time. Eventhough this one depends on how you do the code and cant be guaranteed.</p>
<p><br /> <strong>But, It&rsquo;s Run Perfectly, Should We Change It?</strong> <br /> <br /> Obviously the answer is big NO. This is only the case study and for your further experience and knowledge. OOP is good, do it anywhere it&rsquo;s applicable. But the most important thing is, if it&rsquo;s running, dont change it. It would be ridiculous if you ruin the entire working code just to pursue some OOP approach. Dont be naive also, no one can achieve the perfect code. The most important is we know what is the better approach.</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p><a href="http://namingexception.wordpress.com/2012/10/17/case-study-factory-design-pattern/">ref:http://namingexception.wordpress.com/2012/10/17/case-study-factory-design-pattern/</a></p>
