---
layout: post
title: "Use Spring JavaMailSender and Freemarker to send Email by template"
comments: true
---
<p>&nbsp;</p>
<p><span style="font-size: small;">&lt;bean class="org.springframework.mail.javamail.JavaMailSenderImpl" id="mailSender"&gt;</span><br /><span style="font-size: small;">&nbsp; &lt;property name="host" value="${mail.host}"&gt;&lt;/property&gt;</span><br /><span style="font-size: small;">&nbsp; &lt;property name="username" value="${mail.username}"&gt;&lt;/property&gt;</span><br /><span style="font-size: small;">&nbsp; &lt;property name="password" value="${mail.password}"&gt;&lt;/property&gt;</span><br /><span style="font-size: small;">&nbsp; &lt;property name="javaMailProperties"&gt;</span><br /><span style="font-size: small;">&nbsp;&nbsp;&nbsp; &lt;props&gt;</span><br /><span style="font-size: small;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &lt;prop key="mail.smtp.auth"&gt;${mail.smtp.auth}&lt;/prop&gt;</span><br /><span style="font-size: small;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &lt;prop key="mail.smtp.port"&gt;${mail.smtp.port}&lt;/prop&gt;</span><br /><span style="font-size: small;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &lt;prop key="mail.smtp.host"&gt;${mail.host}&lt;/prop&gt;</span><br /><span style="font-size: small;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &lt;prop key="mail.smtp.starttls.enable"&gt;true&lt;/prop&gt;</span><br /><span style="font-size: small;">&nbsp;&nbsp;&nbsp; &lt;/props&gt;</span><br /><span style="font-size: small;">&nbsp; &lt;/property&gt;</span><br /><span style="font-size: small;">&lt;/bean&gt;</span></p>
<p>&nbsp;</p>
<p><span style="font-size: small;">&lt;bean class="org.springframework.ui.freemarker.FreeMarkerConfigurationFactoryBean" id="freemarkerConfiguration"&gt;</span><br /><span style="font-size: small;">&nbsp; &lt;property name="preferFileSystemAccess" value="false"&gt;&lt;/property&gt;</span><br /><span style="font-size: small;">&nbsp; &lt;property name="templateLoaderPath" value="classpath:/"&gt;&lt;/property&gt;</span><br /><span style="font-size: small;">&lt;/bean&gt;</span></p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p><br />&nbsp;<br /><span style="font-size: small;">import java.util.Map;</span><br />&nbsp;<br /><span style="font-size: small;">import javax.mail.internet.MimeMessage;</span><br />&nbsp;<br /><span style="font-size: small;">import org.springframework.mail.javamail.JavaMailSender;</span><br /><span style="font-size: small;">import org.springframework.mail.javamail.MimeMessageHelper;</span><br /><span style="font-size: small;">import org.springframework.mail.javamail.MimeMessagePreparator;</span><br /><span style="font-size: small;">import org.springframework.ui.freemarker.FreeMarkerTemplateUtils;</span><br />&nbsp;<br /><span style="font-size: small;">import freemarker.template.Configuration;</span></p>
<p><br /><span style="font-size: small;">&nbsp;@Service("mailService")</span><br /><span style="font-size: small;">public class MailService {</span><br /><span style="font-size: small;">&nbsp;@Autowired</span><br /><span style="font-size: small;">&nbsp; private JavaMailSender javaMailSender;</span></p>
<p><span style="font-size: small;">@Autowired</span><br /><span style="font-size: small;">&nbsp; private Configuration freemarkerConfiguration;</span><br />&nbsp;&nbsp; <br /><span style="font-size: small;">&nbsp; public void sendMail(final String from, final String to, final String subject, final Map&lt;string object=""&gt; model, final String template){</span><br /><span style="font-size: small;">&nbsp;&nbsp;&nbsp; MimeMessagePreparator preparator = new MimeMessagePreparator() {</span><br /><span style="font-size: small;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; public void prepare(MimeMessage mimeMessage) throws Exception {</span><br /><span style="font-size: small;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; MimeMessageHelper message = new MimeMessageHelper(mimeMessage);</span><br /><span style="font-size: small;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; message.setFrom(from, "azizkhani");</span><br /><span style="font-size: small;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; message.setTo(to);</span><br /><span style="font-size: small;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; message.setSubject(subject);</span><br /><span style="font-size: small;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; //template sample: "freemarker/confirm-register.ftl"</span><br /><span style="font-size: small;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; String text =FreeMarkerTemplateUtils.processTemplateIntoString(freemarkerConfiguration.getTemplate(template,"UTF-8"), model);</span><br /><span style="font-size: small;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; message.setText(text, true);</span><br /><span style="font-size: small;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; }</span><br /><span style="font-size: small;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; };</span><br /><span style="font-size: small;">&nbsp;&nbsp;&nbsp; javaMailSender.send(preparator);</span><br /><span style="font-size: small;">&nbsp; }</span><br />&nbsp;<br /><span style="font-size: small;">}</span><br /><br /></p>
<p>&nbsp;</p>
